apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
spec:
  selector:
    matchLabels:
      stack: !Var nodeapp_name
      component: node
  template:
    metadata:
      labels:
        stack: !Var nodeapp_name
        component: node
    spec:
      enableServiceLinks: false
      securityContext: !Var node_pod_security_context
      initContainers:
        - !If
            test: !Var nodeapp_setup_should_run
            then:
              name: setup
              image: !Var nodeapp_image
              args: !Var nodeapp_setup_command
              env: !Var node_environment
              securityContext: !Var node_container_security_context
      containers:
        - name: node
          image: !Var nodeapp_image
          ports:
            - containerPort: 3000
          env: !Var node_environment
          securityContext: !Var node_container_security_context
          startupProbe:
            httpGet:
              path: /healthz
              port: 3000
              httpHeaders:
                - name: Host
                  value: !Var ingress_public_hostname
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
              httpHeaders:
                - name: Host
                  value: !Var ingress_public_hostname
            periodSeconds: 30
          volumeMounts:
            - mountPath: /tmp
              name: temp
      volumes:
        - name: temp
          emptyDir: {}
