apiVersion: v1
kind: Service
metadata:
  name: node
  labels:
    stack: !Var nodeapp_name
    component: node
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    stack: !Var nodeapp_name
    component: node
