nodeapp_secret_managed: false
nodeapp_admins:
  - Santtu Pajukanta <santtu@pajukanta.fi>
nodeapp_allowed_hosts:
  - !Var ingress_public_hostname
nodeapp_extra_env:
  - name: INFOKALA_DEFAULT_EVENT
    value: tracon2021

ingress_public_hostname: infotv.tracon.fi

postgres_managed: false
postgres_hostname: siilo.tracon.fi
postgres_database: infotv
postgres_username: infotv
postgres_ssl: true

nodeapp_setup_should_run: true

nodeapp_smtp_server: sr1.pahaip.fi
nodeapp_smtp_default_from_email: root@tracon.fi

ingress_letsencrypt_enabled: true
ingress_letsencrypt_cluster_issuer: letsencrypt-prod
