apiVersion: apps/v1
kind: Deployment
metadata:
  name: !Var project_name
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: !Var project_name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: !Var project_name
    spec:
      containers:
        - name: !Var project_name
          image: !Var project_name
